["x86_64-linux"]
url = "https://files.pythonhosted.org/packages/07/ce/fe29a74c6af4dae88b0146b4a8c4a79b4ca3cf400ae08dd401a13f52305a/mediapipe-0.10.31-py3-none-manylinux_2_28_x86_64.whl"
hash = "sha256-Ng3oliBYIkGbFNdXTCgS4IlGdpIo91SMMd2HGxUNm8w="
